title = "iBdB Hot Takes"
base_url = "https://ibdb-project.github.io/hot-takes"
description = "iBdB Hot Takes"

compile_sass = true

build_search_index = false

[markdown]
highlight_code = false

[extra]

header_links = []
